name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HRKU-AAHBpMn50Huq0prGCGvDG_x4VWic3FTjia_BmNivYEKg_____wFx_M5x54BS}}
          HEROKU_APP_NAME: "student-performance-pred"
        run: |
          git remote add heroku https://git.heroku.com/student-performance-pred.git
          git push heroku main
